---
- name: install vimiv
  pacman:
    name: vimiv
    state: present
  become: true

- name: create vimiv config directory
  file:
    path: '{{ defaults.config_home }}/vimiv'
    state: directory

- name: configure vimiv
  template:
    src: vimivrc.j2
    dest: '{{ defaults.config_home }}/vimiv/vimivrc'
