---
- name: check if yaourt is installed
  command: pacman -Q yaourt
  register: installed
  changed_when: False
  ignore_errors: True

- include_tasks: install.yml
  when: installed|failed

- name: create yaourt config directory
  file:
    path: '{{ ansible_env.XDG_CONFIG_HOME }}/yaourt'
    state: directory

- name: configure yaourt
  template:
    src: yaourtrc.j2
    dest: '{{ ansible_env.XDG_CONFIG_HOME }}/yaourt/yaourtrc'
