---
- hosts: localhost
  roles:
    - role: env-vars
    - role: xdg-user-dirs
    - role: deepin-tools
    - role: dunst
    - role: termite
    - role: ranger
    - role: redshift
    - role: gtk3
    - role: vimiv
