---
- hosts: localhost
  roles:
    - role: yaourt
      tags: yaourt

    - role: env-vars
      tags: env-vars

    - role: xdg-user-dirs
      tags: xdg-user-dirs

    - role: fish
      tags: fish

    - role: qtile
      tags: qtile

    - role: vim
      tags: vim

    - role: deepin-tools
      tags: deepin-tools

    - role: dunst
      tags: dunst

    - role: termite
      tags: termite

    - role: ranger
      tags: ranger

    - role: redshift
      tags: redshift

    - role: gtk3
      tags: gtk3

    - role: vimiv
      tags: vimiv

    - role: taskwarrior
      tags: taskwarrior
