---
- name: install deepin tools
  pacman:
    name: deepin-{{ item }}
    state: present
  become: true
  with_items: '{{ tools }}'

- name: create config directories
  file:
    path: '{{ defaults.config_home }}/deepin/deepin-{{ item }}'
    state: directory
  with_items: '{{ tools }}'

- name: configure deepin tools
  template:
    src: deepin-{{ item }}.conf.j2
    dest: '{{ defaults.config_home }}/deepin/deepin-{{ item }}/config.conf'
  with_items: '{{ tools }}'

