---
- name: install deepin tools
  pacman:
    name: deepin-{{ item }}
    state: present
  become: true
  with_items: '{{ tools }}'

- name: create config directories
  file: 
    path: '{{ ansible_env.XDG_CONFIG_HOME }}/deepin/deepin-{{ item }}'
    state: directory
  with_items: '{{ tools }}'

- name: configure deepin tools
  template:
    src: deepin-{{ item }}.conf.j2
    dest: '{{ ansible_env.XDG_CONFIG_HOME }}/deepin/deepin-{{ item }}/config.conf'
  with_items: '{{ tools }}'

