---
- name: set the icon directory as a variable for the task
  command: echo {{ ansible_user_dir }}/.papirus-dark
  register: icon_dir
  changed_when: False

- name: find audio and battery icons
  find:
    paths: /usr/share/icons/Papirus-Dark/symbolic/status
    patterns: 'audio-*,battery-*'
  register: find_result

- name: make sure the .papirus-dark directory is present
  file:
    path: '{{ icon_dir.stdout }}'
    state: directory

- name: retrieve already converted icons
  command: ls {{ icon_dir.stdout }}
  register: list_icons
  changed_when: False

- name: converts the svg icons to png icons
  shell: >
    rsvg-convert -w 1024 -h 1024 {{ item.path }} >
    {{ icon_dir.stdout }}/{{ (item.path|basename)|replace('-symbolic.svg', '.png') }}
  changed_when: False
  with_items: '{{ find_result.files }}'
  when: >
    (item.path|basename)|replace('-symbolic.svg', '.png')
    not in list_icons.stdout_lines
