---
- name: install ranger
  pacman:
    name: ranger
    state: present
  become: true

- name: create ranger config directory
  file:
    path: '{{ defaults.config_home }}/ranger'
    state: directory

- name: configure ranger
  template:
    src: rc.conf.j2
    dest: '{{ defaults.config_home }}/ranger/rc.conf'
