---
- name: install termite
  pacman:
    name: termite
    state: present

- name: create termite config directory
  file:
    path: '{{ defaults.config_home }}/termite'
    state: directory

- name: configure termite
  template:
    src: config.j2
    dest: '{{ defaults.config_home }}/termite/config'
