---
- name: install dunst
  pacman:
    name: dunst
    state: present
  become: true

- name: create dunst config directory
  file:
    path: '{{ defaults.config_home }}/dunst'
    state: directory

- name: configure dunst
  template:
    src: dunstrc.j2
    dest: '{{ defaults.config_home }}/dunst/dunstrc'
