---
- name: create gtk3 config directory
  file: path={{ ansible_env.XDG_CONFIG_HOME }}/gtk-3.0 state=directory

- name: configure gtk3
  template: src=settings.ini.j2 dest={{ ansible_env.XDG_CONFIG_HOME }}/gtk-3.0/settings.ini
